### ISSUE TITLE
Generates blank page in PDF

### ISSUE THREAD

**Issue by sharathm89** [PejmanNik/jikji#8] opened 2023-06-16 18:29 UTC
The below creates a Cover page with background image (Later i'll put some title and other information on it)

It shows perfectly on website but when pdf is generated it creates an emtpy page after the cover page.

Attaching the website image and pdf generated.

```
import { Image, usePageInfo } from "@jikji/react";

function Cover() {
  const { pageDimension } = usePageInfo();

  return (
    <ReportView>
      <ReportRoot>

        <Section dimension={pageSize.A4}>
          <PageContent>
            <div style={{ height: pageDimension.height }}>
              <Image
                width="100%"
                height="100%"
                src="https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba"
              />
              </div>
          </PageContent>
        </Section>

      </ReportRoot>
    </ReportView>
  );
}

export default Cover;
```

## Website Result

<img width="606" alt="Screenshot 2023-06-16 at 12 09 51 PM" src="https://github.com/PejmanNik/jikji/assets/17666778/ac19592e-2316-413e-9231-34e5d1871efa">

## PDF Generated using **@jikji/generator**

[out.pdf](https://github.com/PejmanNik/jikji/files/11773670/out.pdf)

**Comment by PejmanNik** [comment] 2023-06-18 07:08
Hi, yes it seems it is caused by the change of behavior in browsers (or I don't know why), but you can use a custom size to page size and use a smaller size than the actual Page standard. you can use this file as a reference. It will be fixed in the next version

https://github.com/PejmanNik/jikji/blob/add-e2e-tests/packages/react/src/core/pageConst.ts

**Closed** 2023-06-18 07:08 UTC
