### ISSUE TITLE
Table Header repeats multiple times

### ISSUE THREAD

**Issue by sharathm89** [PejmanNik/jikji#13] opened 2023-07-04 21:22 UTC
Few issues in Table

- Table header repeats in few scanerios (refer to 1st and 2nd image)
- Last row from table displays partial information in 1 page and other row details in next page (refer to 3rd image)

Here is the github repo link which demonstrates  table (issues) in it.  (checkout the readme file)
 
[Repo Link](https://github.com/sharathm89/report-app)

### **Image 1 - header repeating**

<img width="799" alt="Screenshot 2023-07-04 at 2 19 13 PM" src="https://github.com/PejmanNik/jikji/assets/17666778/702dc0ac-6726-479b-bb24-a2d87ac0322f">

### **Image 2- header repeating**

<img width="805" alt="Screenshot 2023-07-04 at 2 19 22 PM" src="https://github.com/PejmanNik/jikji/assets/17666778/ee0b73dd-0f23-4713-91db-e8f960cc37c1">

### **Image 3 - last row from page is truncatted and remaining displayed in next page**

<img width="797" alt="Screenshot 2023-07-04 at 2 19 33 PM" src="https://github.com/PejmanNik/jikji/assets/17666778/169b82de-9087-4c91-ae48-7f40eab595d1">

**Comment by sharathm89** [comment] 2023-07-07 20:45
@PejmanNik  these table issues are freqently occuring ..   apart from the table issues the library is amazing to develop reports...

**Comment by PejmanNik** [comment] 2023-07-08 13:00
I'll try to find the issue, but you are using the library wrongly. if you want to load static JSON data please check [inject JSON data](https://jikji.xyz/docs/inject-json-data), basically if the page is not instantly ready to be parsed (like how you are reading the JSON file) you need to notify the library to wait for it. 

You can use that Inject JSON data component or the using the [use-layout-suspension](https://jikji.xyz/docs/components/utilize/use-layout-suspension) hook to build your own version of it

**Comment by PejmanNik** [comment] 2023-07-08 16:56
The header duplication should be fixed in v0.3.2, I couldn't reproduce the second one, can you please check it again with the last version?

**Comment by sharathm89** [comment] 2023-07-09 06:48
header duplication issue seems to be fixed...  Other issue let me do a workaround as per your suggestions... 

But ideally in my scanerio I would be making api call to fetch the data (Loading data through JSON files is for testing purpose)

**Comment by PejmanNik** [comment] 2023-07-09 06:58
Ok good to know. So I'll close this issue

For API call you can check this Component: [QuoteFromAPI](https://github.com/PejmanNik/jikji/blob/main/example/src/AnnualReport/QuoteFromAPI.tsx)

Components will mount and unmount during the layout process at least two times. In order to have better performance, it is better to use a library like react-query that cache the API response. So the component only gets the data one time per layout.

**Closed** 2023-07-09 06:58 UTC
Labels: bug
